### ISSUE TITLE
The tag and the file name do not mesh release on github

### ISSUE THREAD

**Issue by uga-rosa** [b4b4r07/afx#42]
## WHAT

Sometimes, as in this [lazygit](https://github.com/jesseduffield/lazygit/releases/tag/v0.34), the tag is v0.34 but the filename uses 0.34 instead of v0.34.

I can't use `.Release.Tag` in assets, what should I do?

**Comment by babarot** [comment]
@uga-rosa 

Hi, thank you for using this tool.

Maybe you can use `replace` function like:

```yaml
    asset:
      filename: '{{ .Release.Name }}_{{ replace .Release.Tag "v" "" }}_{{ .OS }}_{{ .Arch }}.tar.gz'
```

I will add the usage of builtin function to the document.

**Comment by uga-rosa** [comment]
Thank you!!
