### ISSUE TITLE
Behavior of "afx install" on local package

### ISSUE THREAD

**Issue by shihanng** [b4b4r07/afx#54]
## WHAT

It seems that `afx install` does not trigger the "Command" and "Plugin" installations under "local package".

https://github.com/b4b4r07/afx/blob/e9d6a7d4cb0850a25daea3518b023b7de628e289/pkg/config/local.go#L36-L39

## WHY

Is this intended?

**Comment by babarot** [comment]
Yes. Most of the time, local packages don't need to be installed because those are already located on your filesystem.

**Comment by babarot** [comment]
Thank you for the comment. Related to #53 question

**Comment by babarot** [comment]
Not fixed

**Comment by babarot** [comment]
Fixed on v0.1.26
