### ISSUE TITLE
Token information. '?' not doing anything when asked to 'input for more info'.

### ISSUE THREAD

**Issue by MostHated** [b4b4r07/afx#55]
Hello,
    I tried to run an install for the first time and it said I needed a token and to input '?' for more info. I hit '?' and nothing occurred, so I hit enter, got bad credentials for Github token. 
I then Checked --help, saw nothing in regards to adding a token. I checked the docs site, searched the pages for Token and got no hits. I tried to search for 'token' here in the issues, no hits.  

Not sure what I am to do here. I don't know what kind of token/permissions it requires, and I don't see this info anywhere.  

Thanks,

**Comment by babarot** [comment]
Please add repo scope to a token.

![Screenshot 2023-03-02 at 12 09 19](https://user-images.githubusercontent.com/4442708/222321153-b205976b-b29c-4c6f-a47b-aba24ede9def.png)
